/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestFrame.java
 *
 * Created on 09.02.2009, 18:51:53
 */

package client;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;


/**
 *
 * @author Admin
 */
public class TestFrame extends javax.swing.JFrame implements WindowListener{

    String url;


    private client.LoginPanel loginPanel1;

    /** Creates new form TestFrame */
    public TestFrame() {

		loginPanel1 = null;
        initComponents();
        jMenuBar.setVisible(false);
		this.addWindowListener(this);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        connectionPanel = new javax.swing.JPanel();
        guiPanel = new javax.swing.JPanel();
        ipAddressLabel = new javax.swing.JLabel();
        ipAddressTextField = new javax.swing.JTextField();
        connectBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addMoneyBtn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        logoutBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        connectionPanel.setPreferredSize(new java.awt.Dimension(1050, 700));
        connectionPanel.setLayout(new java.awt.BorderLayout());

        guiPanel.setBackground(new java.awt.Color(0, 102, 0));
        guiPanel.setLayout(new java.awt.GridBagLayout());

        ipAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 18));
        ipAddressLabel.setForeground(new java.awt.Color(153, 255, 0));
        ipAddressLabel.setText("IP address:");
        guiPanel.add(ipAddressLabel, new java.awt.GridBagConstraints());

        ipAddressTextField.setBackground(new java.awt.Color(51, 204, 0));
        ipAddressTextField.setFont(new java.awt.Font("Tahoma", 1, 18));
        ipAddressTextField.setText("localhost");
        ipAddressTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ipAddressTextField.setPreferredSize(new java.awt.Dimension(150, 25));
        ipAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipAddressTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        guiPanel.add(ipAddressTextField, gridBagConstraints);

        connectBtn.setBackground(new java.awt.Color(0, 153, 51));
        connectBtn.setForeground(new java.awt.Color(153, 255, 0));
        connectBtn.setText("Connect");
        connectBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        connectBtn.setPreferredSize(new java.awt.Dimension(80, 25));
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        guiPanel.add(connectBtn, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("(Ex: 129.234.13.13, localhost)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        guiPanel.add(jLabel1, gridBagConstraints);

        connectionPanel.add(guiPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(connectionPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        addMoneyBtn.setText("Add money");
        jMenu1.add(addMoneyBtn);
        jMenu1.add(jSeparator1);

        logoutBtn.setText("Logout");
        jMenu1.add(logoutBtn);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ipAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipAddressTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ipAddressTextFieldActionPerformed

    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
        // TODO add your handling code here:
        url = ipAddressTextField.getText();

        connectionPanel.removeAll();
        loginPanel1 = new client.LoginPanel(url, jMenuBar, addMoneyBtn,logoutBtn);
        connectionPanel.add(loginPanel1, java.awt.BorderLayout.CENTER);
        connectionPanel.revalidate();

}//GEN-LAST:event_connectBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addMoneyBtn;
    private javax.swing.JButton connectBtn;
    private javax.swing.JPanel connectionPanel;
    private javax.swing.JPanel guiPanel;
    private javax.swing.JLabel ipAddressLabel;
    private javax.swing.JTextField ipAddressTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem logoutBtn;
    // End of variables declaration//GEN-END:variables

    public void windowOpened(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

	/**
	 * Called when we close the window
	 * @param e
	 */
    public void windowClosing(WindowEvent e) {
        if(loginPanel1 != null){
			loginPanel1.logout();
		}
    }

    public void windowClosed(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowIconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowActivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

}
